### ISSUE TITLE
Linking to repos

### ISSUE THREAD

**Issue by theo-armour** [opentecture/opentecture-web-old#1]
@afomi 

Neither of these links work:
https://www.opentecture.com/mindmapping/README.md
https://opentecture.github.io/mindmapping/README.md

Linking via a CDN works but is not pretty:
https://rawgit.com/opentecture/mindmapping/master/#README.md 

Any ideas on getting pretty links to work?

**Comment by afomi** [comment]
hi @theo-armour - I'm just getting familiar with PushMe PullYou. I don't know that I'd expect the basic READMEs to show, without the `rawgit` version. Maybe I'm missing something.

Something to discuss perhaps... I do like seeing a live page. Seeing it from the README is new to me. 

My inclination is to use basic html, `raw` or likely through GitHub pages, which is a Jekyll-based publishing system.  I'd rely on the GitHub directory and file management for navigation. 

With that light opinion shared, I don't feel strongly about it.

**Comment by afomi** [comment]
@theo-armour - the website is not currently hosted via GitHub. I think that's why the pretty links don't work.

**Comment by theo-armour** [comment]
@afomi 

Got it. Silly me for thinking the site was hosted on GitHub,

In any case, if you - or I - create a repo titled opentecture.github.io then that would allow links like https://opentecture.github.io/mindmapping to work

**Comment by afomi** [comment]
@theo-armour - the link you posted should now work.

This repo had a `CNAME` file that was redirecting. The file has been removed, which allowed the URL to resolve properly.
