### ISSUE TITLE
Adding new team members

### ISSUE THREAD

**Issue by theo-armour** [opentecture/opentecture-web-old#2]
@afomi 

May I have the authority to invite new members to team mailing lists. I'd like to add Michal to the mindmapping team titled 'the brains'

**Comment by afomi** [comment]
@theo-armour - I upped your permissions at the org level. Let me know if you need additional perms.

**Comment by theo-armour** [comment]
@afomi 

Looks like I still cannot invite peeps - such as Michal - to join us.

**Comment by afomi** [comment]
@theo-armour - can you try once more? You're now an `Owner`

**Comment by theo-armour** [comment]
@afomi 

Thank you, I will do my best to be ethical and respectful of the position.

I just invited Michal. Interesting that you have to be at owner level to send invites.

**Comment by theo-armour** [comment]
All seems good
